target: is_fraud
test_size: 0.2
random_state: 42
model:
  type: logistic_regression
  params:
    max_iter: 600
features:
  drop:
    - transaction_id
    - account_id
    - customer_id
    - timestamp
    - merchant_category
    - device_id
    - ip_address
